version: '3'

services:
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
    volumes:
      - redist:/data

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=accounts
    volumes:
      - posty:/var/lib/postgresql/data
volumes:
  posty:
  redist:

    
    